### ISSUE TITLE
Current time going over media length

### ISSUE THREAD

**Issue by Mr-KayJayDee** [cstefFlexin/web-player#1]
I have uploaded a MP4 video and when it plays the current time counter doesn't stop at the max length of the media and goes over it.

![Screenshot_20210820-232537_Chrome.png](https://user-images.githubusercontent.com/46600662/130294969-aca44a60-c0c3-4c63-a08b-ae0af6b54183.png)

**Comment by cestef** [comment]
I'll look into that later today, thanks for reporting ! ^^

**Comment by cestef** [comment]
Hey, I couldn't reproduce the problem on mobile, I think this is due to putting the app in background and thus the timer continues even though it's not playing, I'll try to fix that. Thanks again :)

**Comment by Mr-KayJayDee** [comment]
If you want I can test further ^^

**Comment by cestef** [comment]
If you have time to do so, would be great if you could dig further into this !

**Comment by Mr-KayJayDee** [comment]
Alright, so.

Clicking on the play button after the file ended playing make this bug appear.

I guess it should replay the file or play the next file in queue (if there is one)

**Comment by cestef** [comment]
Thank you ! I finally decided to switch from AudioBuffer to simply Audio by creating an object url instead of decoding thing etc. This should fix everything (I hope). The bug came from my messy way to detect the current position of the playback ^^'
